# Generated by Django 5.1.4 on 2025-02-26 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ad_userprofile_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Ad',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
